### ISSUE TITLE
PageRank: NoMethodError: undefined method `-' for nil:NilClass

### ISSUE THREAD

**Issue by maia** [louismullie/graph-rank#1]
There's a problem with PageRank calculation: whenever you add a source that's not the destination of any other source, you end up with:

```
lib/graph-rank/page_rank.rb:67:in `block in convergence'
lib/graph-rank/page_rank.rb:66:in `each'
lib/graph-rank/page_rank.rb:66:in `convergence'
lib/graph-rank/page_rank.rb:40:in `calculate'
```

E.g. try:

```
pr = GraphRank::PageRank.new
pr.add 1,2
pr.add 3,1
pr.calculate
```

**Comment by strivemag** [comment]
Hey @louismullie , what does may cause this issue?
